# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tips from Brock
email: brockfanning@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here you will find tips from Brock (Fanning), on subjects ranging from web
  development, to nylon-string guitar, to anger management, along with a
  smattering of cartoon humor and/or short fiction.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://brock.tips" # the base hostname & protocol for your site
twitter_username: brockfanning
github_username: brockfanning
drupal_username: brockfanning

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
